//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_customer()
        {
            this.DD_Orders = new HashSet<DD_Orders>();
        }
    
        public string Profile_Name { get; set; }
        public string Recipient_s_name { get; set; }
        public string Recipient_s_phone { get; set; }
        public string Recipient_s_Email { get; set; }
        public string Shipping_address { get; set; }
        public string Shipping_city { get; set; }
        public string Shipping_post_code { get; set; }
        public int index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Orders> DD_Orders { get; set; }
    }
}
