//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_Orders()
        {
            this.DD_Order_detail = new HashSet<DD_Order_detail>();
        }
    
        public string Order_number { get; set; }
        public string Sales_Channel { get; set; }
        public Nullable<System.DateTime> Created_Order_at { get; set; }
        public Nullable<System.DateTime> Checkout_at { get; set; }
        public Nullable<System.DateTime> Paid_at { get; set; }
        public string Shipping_provider { get; set; }
        public string Shipping_method { get; set; }
        public string Shipping_fee { get; set; }
        public string Payment_method { get; set; }
        public string Variant_Name1 { get; set; }
        public string Variant_Name2 { get; set; }
        public string Bill_discount { get; set; }
        public string Rabbit_LINE_Pay_Coupon { get; set; }
        public string LINE_POINTS { get; set; }
        public string Tracking_code { get; set; }
        public string Tracking_URL { get; set; }
        public string Payment_status { get; set; }
        public string Shipping_status { get; set; }
        public string Order_status { get; set; }
        public Nullable<System.DateTime> Canceled_at { get; set; }
        public string Canceled_reason { get; set; }
        public string Seller_notes { get; set; }
        public string Buyer_notes { get; set; }
        public string status { get; set; }
        public string Order_number_Line { get; set; }
        public Nullable<int> customerId { get; set; }
        public int index { get; set; }
    
        public virtual DD_customer DD_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Order_detail> DD_Order_detail { get; set; }
    }
}
