//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Order_detail
    {
        public Nullable<int> Order_number { get; set; }
        public Nullable<int> Selling_Price { get; set; }
        public Nullable<int> Full_Price { get; set; }
        public string Product_code { get; set; }
        public Nullable<int> SKU_code { get; set; }
        public string Barcode { get; set; }
        public string Product_Name { get; set; }
        public string status_order { get; set; }
        public Nullable<int> Item_quantity { get; set; }
        public int index { get; set; }
    
        public virtual DD_Inventories DD_Inventories { get; set; }
        public virtual DD_Orders DD_Orders { get; set; }
    }
}
