//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrolladdress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enrolladdress()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int addressId { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> numVil { get; set; }
        public string tambol { get; set; }
        public string amper { get; set; }
        public string province { get; set; }
        public string codeCity { get; set; }
        public Nullable<int> status { get; set; }
        public int codeAddress { get; set; }
        public Nullable<int> nameVil { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
