//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentsData
    {
        public string id { get; set; }
        public string idcard { get; set; }
        public string idstudent { get; set; }
        public string classroom { get; set; }
        public string name { get; set; }
        public string birthday { get; set; }
        public string sex { get; set; }
        public string nation { get; set; }
        public string region { get; set; }
        public string status { get; set; }
        public string timeSave { get; set; }
        public string offam { get; set; }
        public string codeaddress { get; set; }
        public string numaddress { get; set; }
        public string groupAddress { get; set; }
        public string soi { get; set; }
        public string road { get; set; }
        public string tambol { get; set; }
        public string ampher { get; set; }
        public string province { get; set; }
        public string posscode { get; set; }
        public string tel { get; set; }
        public string firstTimeClassroom { get; set; }
        public string idcardFather { get; set; }
        public string titleFather { get; set; }
        public string nameFather { get; set; }
        public string statusFather { get; set; }
        public string nationFather { get; set; }
        public string idcardMother { get; set; }
        public string titleMother { get; set; }
        public string nameMother { get; set; }
        public string statusMother { get; set; }
        public string nationMother { get; set; }
        public string idcardPoten { get; set; }
        public string titlePoten { get; set; }
        public string namePoten { get; set; }
        public string statusPoten { get; set; }
        public string nationPoten { get; set; }
        public string relationPoten { get; set; }
        public string r15 { get; set; }
    }
}
